/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.95
 * Generated at: 2024-02-17 19:00:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<style>\r\n");
      out.write("		.rq {\r\n");
      out.write("			color: red;\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function my_submit() {\r\n");
      out.write("			error = \"\"\r\n");
      out.write("			// bắt lỗi\r\n");
      out.write("			maSanPham = document.getElementById(\"maSanPham\").value\r\n");
      out.write("			tenSanPham = document.getElementById(\"tenSanPham\").value\r\n");
      out.write("			giaBan = document.getElementById(\"giaBan\").value\r\n");
      out.write("			giaNhap = document.getElementById(\"giaNhap\").value\r\n");
      out.write("			if(maSanPham.length == 0) {\r\n");
      out.write("				error += \"Bạn phải nhập mã sản phẩm!\"\r\n");
      out.write("				error_maSanPham = document.getElementById(\"error_maSanPham\")\r\n");
      out.write("				error_maSanPham.innerHTML = \"<span class='rq'>Bạn phải nhập mã sản phẩm.</span>\"\r\n");
      out.write("			} \r\n");
      out.write("			if(tenSanPham.length == 0) {\r\n");
      out.write("				error += \"Bạn phải nhập tên sản phẩm!\"\r\n");
      out.write("				error_tenSanPham = document.getElementById(\"error_tenSanPham\")\r\n");
      out.write("				error_tenSanPham.innerHTML = \"<span class='rq'> Bạn phải nhập mã sản phẩm.</span>\"\r\n");
      out.write("			} \r\n");
      out.write("			if(giaBan <= 0) {\r\n");
      out.write("				error += \"Bạn phải nhập giá bán!\"\r\n");
      out.write("				error_giaBan = document.getElementById(\"error_giaBan\")\r\n");
      out.write("				error_giaBan.innerHTML = \"<span class='rq'> Bạn phải nhập giá bán. </span>\"\r\n");
      out.write("			}\r\n");
      out.write("			if(giaNhap <= 0) {\r\n");
      out.write("				error += \"Bạn phải nhập giá nhập!\"\r\n");
      out.write("				error_giaNhap = document.getElementById(\"error_giaNhap\")\r\n");
      out.write("				error_giaNhap.innerHTML = \"<span class='rq'> Bạn phải nhập giá nhập. </span>\"\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if(error.length > 0) {\r\n");
      out.write("				// alert(error)\r\n");
      out.write("				return\r\n");
      out.write("			} else {			\r\n");
      out.write("				// submit form\r\n");
      out.write("				my_form = document.getElementById(\"my_form\").value\r\n");
      out.write("				my_form.submit()\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	String e_maSanPham = request.getAttribute("e_maSanPham") + "";
	if(e_maSanPham == null || e_maSanPham.equals("null")) {
		e_maSanPham = "";
	}

	String value_maSanPham = request.getAttribute("value_maSanPham") + "";
	String value_tenSanPham = request.getAttribute("value_tenSanPham") + "";
	String value_giaBan = request.getAttribute("value_giaBan") + "";
	String value_giaNhap = request.getAttribute("value_giaNhap") + "";
	String value_hanSuDung = request.getAttribute("value_hanSuDung") + "";
	String value_vat = request.getAttribute("value_vat") + "";
	String value_moTa = request.getAttribute("value_moTa") + "";
	
	value_maSanPham = (value_maSanPham.equals("null")) ? "" : value_maSanPham; 
	value_tenSanPham = (value_tenSanPham.equals("null")) ? "" : value_tenSanPham;
	value_giaBan = (value_giaBan.equals("null")) ? "" : value_giaBan;
	value_giaNhap = (value_giaNhap.equals("null")) ? "" : value_giaNhap;
	value_hanSuDung = (value_hanSuDung.equals("null")) ? "" : value_hanSuDung;
	value_vat = (value_vat.equals("null")) ? "" : value_vat;
	value_moTa = (value_moTa.equals("null")) ? "" : value_moTa;


      out.write("\r\n");
      out.write("	<div class=\"container mt-4\">\r\n");
      out.write("		<form class=\"row g-3 needs-validation\" action=\"save-product\" id=\"my_form\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-6\">\r\n");
      out.write("					<label for=\"maSanPham\" class=\"form-label\">\r\n");
      out.write("						Mã sản phẩm <span class=\"rq\">*</span>\r\n");
      out.write("					</label> \r\n");
      out.write("					<input type=\"text\" class=\"form-control\" id=\"maSanPham\" name=\"maSanPham\" value=\"");
      out.print(value_maSanPham );
      out.write("\" required>\r\n");
      out.write("					<!-- <div id=\"error_maSanPham\"></div> -->\r\n");
      out.write("					<div class=\"rq\">");
      out.print(e_maSanPham );
      out.write("</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-6\">\r\n");
      out.write("					<label for=\"tenSanPham\" class=\"form-label\">\r\n");
      out.write("						Tên sản phẩm <span class=\"rq\">*</span>\r\n");
      out.write("					</label> \r\n");
      out.write("					<input type=\"text\" class=\"form-control\" id=\"tenSanPham\" name=\"tenSanPham\" value=\"");
      out.print(value_tenSanPham );
      out.write("\" required>\r\n");
      out.write("					<div id=\"error_tenSanPham\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-6\">\r\n");
      out.write("					<label for=\"giaNhap\" class=\"form-label\">\r\n");
      out.write("						Giá nhập <span class=\"rq\">*</span>\r\n");
      out.write("					</label> \r\n");
      out.write("					<input type=\"number\" step=\"0.01\" class=\"form-control\" id=\"giaNhap\" name=\"giaNhap\" min=\"0\" value=\"");
      out.print(value_giaNhap );
      out.write("\" required>\r\n");
      out.write("					<div id=\"error_giaNhap\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-6\">\r\n");
      out.write("					<label for=\"giaBan\" class=\"form-label\">\r\n");
      out.write("						Giá bán <span class=\"rq\">*</span>\r\n");
      out.write("					</label> \r\n");
      out.write("					<input type=\"number\" step=\"0.01\" class=\"form-control\" id=\"giaBan\" name=\"giaBan\" min=\"0\" value=\"");
      out.print(value_giaBan );
      out.write("\" required>\r\n");
      out.write("					<div id=\"error_giaBan\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-6\">\r\n");
      out.write("					<label for=\"hanSuDung\" class=\"form-label\">\r\n");
      out.write("						Hạn sử dụng\r\n");
      out.write("					</label> \r\n");
      out.write("					<input type=\"date\" class=\"form-control\" id=\"hanSuDung\" name=\"hanSuDung\" value=\"");
      out.print(value_hanSuDung );
      out.write("\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-6\">\r\n");
      out.write("					<label for=\"vat\" class=\"form-label\">\r\n");
      out.write("						VAT\r\n");
      out.write("					</label> \r\n");
      out.write("					<input type=\"number\" class=\"form-control\" id=\"vat\" name=\"vat\" value=\"");
      out.print(value_vat );
      out.write("\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<label for=\"moTa\" class=\"form-label\">\r\n");
      out.write("						Mô tả sản phẩm\r\n");
      out.write("					</label> \r\n");
      out.write("					<textarea class=\"form-control\" rows=\"10\" cols=\"\" id=\"moTa\" name=\"moTa\" >");
      out.print(value_moTa );
      out.write("</textarea>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row mt-4\">\r\n");
      out.write("				<button class=\"btn btn-primary\" type=\" button\" onclick=\"my_submit()\" >Submit form</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
